[tool.poetry]
name = "chemic"
version = "1.1.0"
description = ""
authors = ["uncenter <me@uncenter.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
